### ISSUE TITLE
No Longer works with Leaflet 1.0

### ISSUE THREAD

**Issue by revivedtitan** [jdfergason/Leaflet.Ellipse#5]

**Comment by zalayeto** [comment]
Any idea how to make it work with leaflet 1.0?

**Comment by revivedtitan** [comment]
I've already created an updated version if you wanted me to upload.

**Comment by jdfergason** [comment]
If you make a pull request I can merge

Jeremy Fergason

Sent from
https://polymail.io/

On Mon, Mar 13, 2017 at 10:31 AM revivedtitan

<
mailto:revivedtitan <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I've already created an updated version if you wanted me to upload.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/jdfergason/Leaflet.Ellipse/issues/5#issuecomment-286182319
, or

**Comment by revivedtitan** [comment]
Sounds good, I'll do that this afternoon after work

**Comment by zalayeto** [comment]
Any progress?

Thanks.

**Comment by revivedtitan** [comment]
I've created the pull request, just waiting for jdfergason to review and complete the merge/addition.

**Comment by jdfergason** [comment]
Pull request closed and updated to 1.0
